// Auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';

// Profile
export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';
export const UNSET_CURRENT_PROFILE = 'UNSET_CURRENT_PROFILE';

// Errors
export const SET_ERRORS = 'SET_ERRORS';
export const UNSET_ERRORS = 'UNSET_ERRORS';
